import { Service } from '@/types';

export const SERVICES: Service[] = [
  { id: 'eletricista', name: 'Eletricista', icon: '⚡' },
  { id: 'encanador', name: 'Encanador', icon: '🔧' },
  { id: 'diarista', name: 'Diarista', icon: '🧹' },
  { id: 'pintor', name: 'Pintor', icon: '🎨' },
  { id: 'jardineiro', name: 'Jardineiro', icon: '🌱' },
  { id: 'marceneiro', name: 'Marceneiro', icon: '🔨' },
  { id: 'pedreiro', name: 'Pedreiro', icon: '🧱' },
  { id: 'chaveiro', name: 'Chaveiro', icon: '🔑' },
  { id: 'tecnico-ar', name: 'Técnico em Ar Condicionado', icon: '❄️' },
  { id: 'motoboy', name: 'Motoboy', icon: '🏍️' },
  { id: 'marido-aluguel', name: 'Marido de Aluguel', icon: '🔧' },
  { id: 'barbeiro', name: 'Barbeiro', icon: '✂️' },
  { id: 'motorista', name: 'Motorista', icon: '🚗' },
  { id: 'cozinheiro', name: 'Cozinheiro', icon: '👨‍🍳' },
  { id: 'personal-trainer', name: 'Personal Trainer', icon: '💪' },
  { id: 'professor-particular', name: 'Professor Particular', icon: '📚' },
  { id: 'massagista', name: 'Massagista', icon: '💆' },
  { id: 'cuidador', name: 'Cuidador de Idosos', icon: '👴' },
  { id: 'babysitter', name: 'Babá', icon: '👶' },
  { id: 'dog-walker', name: 'Passeador de Cães', icon: '🐕' },
  { id: 'veterinario', name: 'Veterinário', icon: '🐾' },
  { id: 'tecnico-informatica', name: 'Técnico em Informática', icon: '💻' },
  { id: 'fotografo', name: 'Fotógrafo', icon: '📸' },
  { id: 'designer', name: 'Designer Gráfico', icon: '🎨' },
  { id: 'contador', name: 'Contador', icon: '📊' },
  { id: 'advogado', name: 'Advogado', icon: '⚖️' },
  { id: 'arquiteto', name: 'Arquiteto', icon: '📐' },
  { id: 'decorador', name: 'Decorador', icon: '🏠' },
  { id: 'organizador', name: 'Organizador Pessoal', icon: '📋' },
  { id: 'costureira', name: 'Costureira', icon: '🧵' },
  { id: 'sapateiro', name: 'Sapateiro', icon: '👞' },
  { id: 'vidraceiro', name: 'Vidraceiro', icon: '🪟' },
  { id: 'serralheiro', name: 'Serralheiro', icon: '🔩' },
  { id: 'tapeceiro', name: 'Tapeceiro', icon: '🛋️' },
  { id: 'dedetizador', name: 'Dedetizador', icon: '🐛' },
  { id: 'limpeza-piscina', name: 'Limpeza de Piscina', icon: '🏊' },
  { id: 'instalador-som', name: 'Instalador de Som', icon: '🔊' },
  { id: 'montador-moveis', name: 'Montador de Móveis', icon: '🪑' },
];

export const NEIGHBORHOODS = [
  'Centro',
  'Copacabana',
  'Ipanema',
  'Botafogo',
  'Flamengo',
  'Tijuca',
  'Barra da Tijuca',
  'Jacarepaguá',
  'Vila Isabel',
  'Maracanã',
  'Lapa',
  'Santa Teresa',
  'Leblon',
  'Gávea',
  'Laranjeiras'
];